name = "BibtexQuery"
defaultTargets = ["BibtexQuery", "«bibtex-query»"]

[[require]]
name = "UnicodeBasic"
scope = "fgdorais"
rev = "869d78784cf1b82c87f023122449566961947d2e"

[[lean_lib]]
name = "BibtexQuery"

[[lean_exe]]
name = "«bibtex-query»"
root = "BibtexQuery.Main"
